services:
  enigma-booking-management:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASS:
      DB_HOST: mysql-db-container
      DB_NAME: enigma-booking
      JWT_KEY: rahasia
      JWT_EXPIRATION: 600
      JWT_APP_NAME: enigma-booking
    depends_on:
      - mysql-db-container
    networks:
      - booking-management-net

  mysql-db-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=enigma-booking
      - MYSQL_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - booking-management-net

networks:
  booking-management-net:
    driver: bridge

volumes:
  mysql-data: